
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Especifica la tarea a realizar, en este caso ejecutar los test del docker
jobs:
    test_docker:
      machine:
        image: ubuntu-2004:202010-01
      steps:
        - checkout
        - run:
            name: "Test docker app"
            command: |
              docker pull mauronmp/pmp_iv:latest
              docker run -u 1001 -t -v `pwd`:/app/test mauronmp/pmp_iv

# Tareas a realizar, en este caso solo testea el docker
workflows:
  test_my_app:
    jobs:
      - test_docker